apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-burp-scn-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: burp-scan
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"site_id\": \"123\"}"
          - "http://192.168.137.9:9000/"
      restartPolicy: Never
  backoffLimit: 2