apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-burp-scan-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: burp-scan
        image: curlimages/curl
        command:
          - 'curl'
          - '-X'
          - 'POST'
          - '--header='
          - 'Authorization: i1AbNyHDcgMPNtOhFL4MiPiTWoc07fuy'
          - '--header='
          - 'Content-Type: application/json'
          - '--header='
          - 'User-Agent: insomnia/8.6.1'
          - '--data'
          - 'payload={"query":"mutation CreateScheduleItem($input: CreateScheduleItemInput!) {\n  create_schedule_item(input: $input) {\n    schedule_item {\n      id\n    }\n  }\n}","operationName":"CreateScheduleItem","variables":"{\n\t\"input\": {\n\t\t\"site_id\": \"10\",\n\t\t\"schedule\": {},\n\t\t\"scan_configuration_ids\": [],\n\t\t\"verbose_debug\": null\n\t}\n}"}'
          - 'http://192.168.137.9:9000/graphql/v1'
      restartPolicy: Never
  backoffLimit: 2
