apiVersion: batch/v1
kind: Job
metadata:
  generateName: app-burp-scan-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: burp-scan-update-site
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data"
          - "{\"site_id\": \"123\"}"
          - "http://192.168.137.9:9000/burp-scan-update-site"
      - name: burp-scan
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "{\"site_id\": \"123456\"}"
          - "http://192.168.137.9:9000/burp-scan"
      restartPolicy: Never
  backoffLimit: 2
